import { createElement } from '@lwc/engine-dom';
import DeployNewTestTwo from 'c/deployNewTestTwo';

describe('c-deploy-new-test-two', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-deploy-new-test-two', {
            is: DeployNewTestTwo
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});