name: Deploy Salesforce to Main Org

on:
  push:
    branches: [main, UAT]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2

      - name: Fetch base and head branches/commits
        run: |
            git fetch origin ${{ github.event.before }}:${{ github.event.before }}
            git fetch origin ${{ github.sha }}:${{ github.sha }}

      - name: Run generateXML.py
        run: |
          python generateXML.py --base_commit ${{ github.event.before }} --head_commit ${{ github.sha }}

      - name: Set Org Credentials Based on Branch
        run: |
          BRANCH="${GITHUB_REF##*/}"
          echo "Branch: $BRANCH"

          if [[ "$BRANCH" == "main" ]]; then
            echo "SF_USERNAME=${{ secrets.SF_USERNAME_MAIN }}" >> $GITHUB_ENV
            echo "SF_CONSUMER_KEY=${{ secrets.SF_CONSUMER_MAIN_KEY }}" >> $GITHUB_ENV
            echo "SF_INSTANCE_URL=${{ secrets.SF_INSTANCE_UAT_URL }}" >> $GITHUB_ENV
          elif [[ "$BRANCH" == "UAT" ]]; then
            echo "SF_USERNAME=${{ secrets.SF_USERNAME_UAT }}" >> $GITHUB_ENV
            echo "SF_CONSUMER_KEY=${{ secrets.SF_CONSUMERUAT_KEY }}" >> $GITHUB_ENV
            echo "SF_INSTANCE_URL=${{ secrets.SF_INSTANCE_UAT_URL }}" >> $GITHUB_ENV
          else
            echo "Unsupported branch: $BRANCH"
            exit 1
          fi

      - name: Decode JWT key
        run: |
          echo "${{ secrets.SF_JWT_SECRET }}" > server.key

      - name: Authenticate with Salesforce (sf CLI)
        run: |
          sf org login jwt \
            --client-id "$SF_CONSUMER_KEY" \
            --jwt-key-file server.key \
            --username "$SF_USERNAME" \
            --instance-url "$SF_INSTANCE_URL" \
            --alias ci-org \
            --set-default

      - name: Deploy Metadata to Salesforce
        run: |
          sf deploy metadata \
            --manifest package.xml \
            --target-org ci-org \
            --test-level RunLocalTests \
            --wait 30 \
            --verbose

      - name: Deploy Destructive Changes (if present)
        if: ${{ hashFiles('destructiveChanges.xml') != '' }}
        run: |
          sf deploy metadata \
            --manifest package.xml \
            --destructive-changes destructiveChanges.xml \
            --target-org ci-org \
            --test-level RunLocalTests \
            --wait 30 \
            --verbose
