name: Deploy Salesforce to Main Org

on:
  push:
    branches: [main, development]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13.2

      - name: Fetch base and head branches/commits
        run: |
            git fetch origin ${{ github.event.before }}:${{ github.event.before }}
            git fetch origin ${{ github.sha }}:${{ github.sha }}

      - name: Run generateXML.py
        run: |
          python generateXML.py --base_commit ${{ github.event.before }} --head_commit ${{ github.sha }}

      - name: Decode JWT key
        run: |
          echo "${{ secrets.SF_JWT_SECRET }}" | base64 --decode > server.key

      - name: Authenticate with Salesforce (sf CLI)
        run: |
          sf org login jwt \
            --client-id ${{ secrets.SF_CONSUMERUAT_KEY }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME_UAT }} \
            --instance-url ${{ secrets.SF_INSTANCE_UAT_URL }} \
            --alias ci-org \
            --set-default

      - name: Deploy Metadata to Salesforce
        run: |
          sf deploy metadata \
            --manifest package.xml \
            --target-org ci-org \
            --test-level RunLocalTests \
            --wait 30 \
            --verbose

      - name: Deploy Destructive Changes (if present)
        if: ${{ hashFiles('destructiveChanges.xml') != '' }}
        run: |
          sf deploy metadata \
            --manifest package.xml \
            --destructive-changes destructiveChanges.xml \
            --target-org ci-org \
            --test-level RunLocalTests \
            --wait 30 \
            --verbose
